export const default_image = require("./Images/default.png")
export const youtube_downloader = require("./Images/youtube_downloader.png")
export const gamelauncher_javascript_electron = require("./Images/gamelauncher_javascript_electron.png")
export const file_tools_python_tkinter = require("./Images/file_tools_python_tkinter.png")
export const dashboard_website_react = require("./Images/dashboard_website_react.png")
export const wmusic_website_react = require("./Images/wmusic_website_react.png")
export const tela_de_cadastro_login_javascript = require("./Images/tela_de_cadastro_login_javascript.png")
export const color_picker_extensao_javascript = require("./Images/color_picker_extensao_javascript.png")
export const to_dolist_react = require("./Images/to_dolist_react.png");
export const pomodoro_react = require("./Images/pomodoro_react.png");
export const texttoascii_react_python = require("./Images/texttoascii_react_python.png");
export const proxy_tools_python = require("./Images/proxy_tools_python.png");
export const jogodaforca_react =require("./Images/jogodaforca_react.png")